# Generated by Django 6.1 on 2026-09-04 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='ល.រ / លេខកូដ')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='សម្គាល់')),
                ('registered_date', models.DateField(auto_now_add=True, verbose_name='ថ្ងៃ ខែ កត់ត្រា')),
                ('status', models.CharField(default='គ្មានទិន្នន័យ', max_length=100, verbose_name='ស្ថានភាព')),
                ('capacity', models.CharField(max_length=50, verbose_name='ទំហំផ្ទុក')),
                ('device_type', models.CharField(max_length=100, verbose_name='ប្រភេទ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/', verbose_name='រូបភាព')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(verbose_name='ថ្ងៃ ខែ ខ្ចី')),
                ('borrow_status', models.CharField(default='គ្មានទិន្នន័យ', max_length=100, verbose_name='ស្ថានភាពខ្ចី')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃ ខែ សង')),
                ('return_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='ស្ថានភាពសង')),
                ('borrowed_by', models.CharField(max_length=150, verbose_name='ខ្ចីដោយ')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='មូលហេតុ')),
                ('other_notes', models.TextField(blank=True, null=True, verbose_name='ផ្សេងៗ')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_logs', to='devices.device', verbose_name='ឧបករណ៍')),
            ],
        ),
    ]
