# Generated by Django 6.1.1 on 2026-09-04 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowlog',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='borrowlog',
            name='return_status',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='id_code',
        ),
        migrations.RemoveField(
            model_name='device',
            name='image',
        ),
        migrations.RemoveField(
            model_name='device',
            name='registered_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='remark',
        ),
        migrations.AddField(
            model_name='borrowlog',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃសងជាក់ស្តែង'),
        ),
        migrations.AddField(
            model_name='borrowlog',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃរំពឹងថានឹងសង'),
        ),
        migrations.AddField(
            model_name='borrowlog',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('Good', 'ល្អ/ធម្មតា'), ('Damaged', 'ខូចខាត/មានបញ្ហា')], default='Good', max_length=50, null=True, verbose_name='ស្ថានភាពឧបករណ៍ពេលសង'),
        ),
        migrations.AddField(
            model_name='borrowlog',
            name='return_image',
            field=models.ImageField(blank=True, null=True, upload_to='return_proofs/', verbose_name='រូបភាពឧបករណ៍ពេលសង'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='', max_length=255, verbose_name='ឈ្មោះឧបករណ៍'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ម៉ូឌែល'),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='លេខស៊េរី (Serial Number)'),
        ),
        migrations.AlterField(
            model_name='borrowlog',
            name='borrow_date',
            field=models.DateField(verbose_name='ថ្ងៃខ្ចី'),
        ),
        migrations.AlterField(
            model_name='borrowlog',
            name='borrow_status',
            field=models.CharField(choices=[('Pending', 'សុំខ្ចី (Pending)'), ('Borrowed', 'កំពុងខ្ចី (Borrowed)'), ('Returned', 'បានសងរួច (Returned)')], default='Pending', max_length=50, verbose_name='ស្ថានភាពខ្ចី'),
        ),
        migrations.AlterField(
            model_name='borrowlog',
            name='borrowed_by',
            field=models.CharField(max_length=255, verbose_name='ឈ្មោះបុគ្គលិកខ្ចី'),
        ),
        migrations.AlterField(
            model_name='borrowlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='ឧបករណ៍'),
        ),
        migrations.AlterField(
            model_name='borrowlog',
            name='other_notes',
            field=models.TextField(blank=True, null=True, verbose_name='កំណត់សម្គាល់'),
        ),
        migrations.AlterField(
            model_name='borrowlog',
            name='reason',
            field=models.TextField(default='', verbose_name='មូលហេតុខ្ចី'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ទំហំផ្ទុក'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Available', 'ទំនេរ'), ('Borrowed', 'កំពុងខ្ចី'), ('Maintenance', 'កំពុងជួសជុល')], default='Available', max_length=50, verbose_name='ស្ថានភាព'),
        ),
    ]
