# Generated by Django 6.1 on 2026-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_device_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='has_data',
            field=models.CharField(choices=[('Yes', 'មានទិន្នន័យ'), ('No', 'មិនមានទិន្នន័យ')], default='No', max_length=10, verbose_name='ស្ថានភាពទិន្នន័យ'),
        ),
    ]
